RITPROJECT/RITPROJECT/college/college/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('collegeapp.urls')),
    # path('',views.members,name="members"),
    # path('te/',views.tem,name="te"),
    # path('index/',views.home,name="index"),
    # path('indexadmin/',views.indexadmin,name="indexadmin"),
    # path('indexadvisor/',views.indexadvisor,name="indexadvisor")
]

RITPROJECT/RITPROJECT/college/collegeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from collegeapp import views

urlpatterns = [
    path('',views.loginpage,name = 'loginpage'),
    path('index_admin/', views.proj, name='projects'),
    path('base/', views.bases, name='bases1'),
    path('regstudent/', views.regstudent, name='regstudent'),
    path('regfaculty/', views.regfaculty, name='regfaculty'),
    path('assign_subject/', views.assignsubject, name='assignsubject1'),
    path('savesub/',views.savesub,name="savesub"),
    path('saveassignsubject/', views.saveassignsubject, name='saveassignsubject'),
    path('assign_advisor/', views.assignadvisor, name='assignadvisor1'),
    path('editadvisor/', views.editadvisor, name='editadvisor'),
    path('update_status/', views.update_status, name='update_status'),
    path('del_student/', views.delstudent, name='delstudent1'),
    path('delstudsave/', views.delstudsave, name='delstudsave'),
    path('result/', views.result, name='result'),
    path('resultview/',views.resultview,name='resultview'),
    path('del_faculty/', views.delfaculty, name='delfaculty1'),
    path('delfacultysave/', views.delfacultysave, name='delfacultysave'),
    path('savesubdel/',views.savesubdel,name='savesubdel'),
    path('sem_updation/', views.semupdation, name='semupdation1'),
    path('select_elective/', views.selectelective, name='selectelective1'),
    path('saveelective/', views.saveelective, name='saveelective'),
    path('batch_students/', views.batch_students, name='batch_students'),
    path('electivestudent/', views.electivestudent, name='electivestudent'),
    path('add_batch/', views.addbatch, name='addbatch1'),
    path('batchdrop/', views.batchdrop, name='batchdrop'),
    path('add_course/', views.addcourse, name='addcourse1'),
    path('add_semester/', views.addsemester, name='addsemester1'),
    path('add_subject/', views.addsubject, name='addsubject1'),
    path('viewbatch/', views.viewbatch, name='viewbatch'),
    path('viewcourse/', views.viewcourse, name='viewcourse'),
    path('viewsemester/', views.viewsemester, name='viewsemester'),
    path('viewsubject/', views.viewsubject, name='viewsubject'),
    path('deletebatch/', views.deletebatch, name='deletebatch'),
    path('savedeletebatch/', views.savedeletebatch, name='savedeletebatch'),
    path('deletecourse/', views.deletecourse, name='deletecourse'),
    path('savedeletecourse/', views.savedeletecourse, name='savedeletecourse'),
    path('deletesemester/', views.deletesemester, name='deletesemester'),
    path('savedeletesem/', views.savedeletesem, name='savedeletesem'),
    path('deletesubject/', views.deletesubject, name='deletesubject'),
    path('indexfaculty/',views.index_faculty,name = 'indexfaculty'),
    path('uploadinternalmark1/',views.upload_internalmark,name = 'uploadinternalmark1'),
    path('saveinteralmark/',views.saveinteralmark,name = 'saveinteralmark'),
    path('saveleave/',views.saveleave,name='saveleave'),
    path('uploadattendance1/',views.upload_attendance,name = 'uploadattendance1'),
    path('dutymedleave1/',views.dutymed_leave,name = 'dutymedleave1'),
    path('index/',views.indexes,name='index'),
    path('save_attendance/',views.save_attendance,name='save_attendance'),
    path('editpersonaldetails/',views.edit_personaldetails,name='editpersonaldetails1'),
    path('viewpersonaldetails/',views.view_personaldetails,name='viewpersonaldetails1'),
    path('viewinternalmark/',views.internalmark,name='viewinternalmark1'),
    path('viewattendance/',views.attendance,name='viewattendance1'),
    path('dutyleave/',views.duty_leave,name='dutyleave1'),
    path('uploadgradecard/',views.upload_gradecard,name='uploadgradecard1'),
    path('process_pdf/',views.process_pdf,name='process_pdf'),
    path('indexadvisor/',views.indexadvisor,name = 'indexadvisor'),
    path('viewpersonalinfo/',views.viewpersonalinfo,name = 'viewpersonalinfo'),
    path('adviewinternalmark/',views.adviewinternalmark,name = 'adviewinternalmark'),
    path('adviewattendance/',views.adviewattendance,name = 'adviewattendance'),
    path('leaveapproval/',views.leaveapproval,name = 'leaveapproval'),
    path('resultanalysis/',views.resultanalysis,name = 'resultanalysis'),
    path('reportgeneration/',views.reportgeneration,name = 'reportgeneration'),
    path('selassign_subject/',views.selassign_subject,name = 'selassign_subject'),
    path('selassign_subject/',views.selassign_subject,name = 'selassign_subject'),
    path('pdf/<str:pdf_filename>/', views.view_uploaded_pdf, name='view_uploaded_pdf'),
    path('contact1/',views.contact1,name = 'contact1'),
    path('btnview/',views.btnview,name = 'btnview'),
    path('btnviewsem/',views.btnviewsem,name = 'btnviewsem'),
    path('btnviewbatch/',views.btnviewbatch,name = 'btnviewbatch'),
    path('edit/',views.edit,name = 'edit'),
    path('studinternalv/',views.studinternalv,name = 'studinternalv'),
    path('attendancesubdt/',views.attendancesubdt,name='attendancesubdt'),
    path('advisorpdview/',views.advisorpdview,name = 'advisorpdview'),
    path('pdf/<int:pdf_id>/',views. view_uploaded_pdf, name='view_uploaded_pdf'),
    path('adviewsub/',views.adviewsub,name='adviewsub'),
    path('stdtadvattendance/',views.stdtadvattendance,name='stdtadvattendance'),
    # path('upload-pdf/', views.upload_pdf, name='upload_pdf'),
    path('facviewinternalmark/',views.facviewinternalmark,name = 'facviewinternalmark'),
    path('facviewattendance/',views.facviewattendance,name = 'facviewattendance'),
    path('facviewsub/',views.facviewsub,name='facviewsub'),
    path('stdtfacattendance/',views.stdtfacattendance,name='stdtfacattendance'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RITPROJECT/RITPROJECT/college/collegeapp/models.py
from django.db import models

# Create your models here.

class Courses(models.Model):
    Course_name = models.TextField()

class Semester(models.Model):
    Courses = models.ForeignKey(Courses,on_delete=models.CASCADE,default=None)
    Semester_name = models.CharField(max_length = 5)

class Batches(models.Model):
    Courses = models.ForeignKey(Courses,on_delete=models.CASCADE,default=None)
    Semester = models.ForeignKey(Semester,on_delete=models.CASCADE,default=None)
    Batch_name = models.CharField(max_length = 15)


class Subjects(models.Model):
    Courses = models.ForeignKey(Courses,on_delete=models.CASCADE,default=None)
    Semester = models.ForeignKey(Semester,on_delete=models.CASCADE,default=None)
    Subject_code = models.CharField(max_length = 6)
    Subject_name = models.CharField(max_length = 75)


class Students(models.Model):
    Batches = models.ForeignKey(Batches,on_delete=models.CASCADE,default=1)
    Username = models.CharField(max_length = 30, default = 'null')
    Pass = models.CharField(max_length = 255, default = 'null')
    KTUID = models.CharField(max_length = 15)
    Admnno = models.CharField(max_length = 15)
    Rollno = models.CharField(max_length = 3)
    Name = models.CharField(max_length = 30)
    Religion = models.CharField(max_length = 15)
    Category = models.CharField(max_length = 30)
    Gender = models.CharField(max_length = 12)
    Dob = models.CharField(max_length = 12)
    Address = models.TextField()
    PhoneNumber = models.CharField(max_length = 10)
    Personalmail = models.EmailField(max_length = 30)
    RITmail = models.EmailField(max_length = 30)
    Nationality = models.CharField(max_length = 20)
    Aadharno = models.CharField(max_length = 12)
    Blood_group = models.CharField(max_length = 15)
    Year_of_admission = models.IntegerField(default=1) 
    Status = models.CharField(max_length = 15)
    Guardian_name = models.CharField(max_length = 30)
    Guardian_contact_no = models.CharField(max_length = 10)

class Electives(models.Model):
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)

class ElectiveChoices(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    Electives = models.ForeignKey(Electives,on_delete=models.CASCADE,default=None)

class Faculties(models.Model):
    Username = models.CharField(max_length = 30, default = 'null')
    Pass = models.CharField(max_length = 255, default = 'null')
    Emp_no = models.CharField(max_length = 15)
    Faculty_name = models.CharField(max_length = 15)

# class Usersstudent(models.Model):
#     Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=1)
#     Username = models.CharField(max_length = 30)
#     Password = models.CharField(max_length = 15)

# class UsersFaculty(models.Model):
#     Faculties = models.ForeignKey(Faculties,on_delete=models.CASCADE,default=1)
#     Username = models.CharField(max_length = 30)
#     Password = models.CharField(max_length = 15)

class Admin(models.Model):
    Username = models.CharField(max_length = 30, default = 'admin')
    Password = models.CharField(max_length = 255, default = 'admin')

class Advisors(models.Model):
    Faculties = models.ForeignKey(Faculties,on_delete=models.CASCADE,default=None)
    Batches = models.ForeignKey(Batches,on_delete=models.CASCADE,default=None)
    
class FacultySubjects(models.Model):
    Faculties = models.ForeignKey(Faculties,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    Batches = models.ForeignKey(Batches,on_delete=models.CASCADE,default=None)

class Attendance(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=1)
    Faculties = models.ForeignKey(Faculties,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    Batches = models.ForeignKey(Batches,on_delete=models.CASCADE,default=None)
    Date = models.DateField()
    Hour = models.IntegerField()
    Status = models.CharField(max_length = 7,default='P')

class SeriesExamMarks(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    SeriesExamNo = models.IntegerField()
    Marks = models.FloatField()

class AssignmentMarks(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    AssignmentNo = models.IntegerField()
    Marks = models.FloatField()

class InternalMarks(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    FacultySubjects = models.ForeignKey(FacultySubjects,on_delete=models.CASCADE,default=None)
    SeriesExamMarks = models.ForeignKey(SeriesExamMarks,on_delete=models.CASCADE,default=None)
    AssignmentMarks = models.ForeignKey(AssignmentMarks,on_delete=models.CASCADE,default=None)
    Attendancemarks = models.IntegerField()
    Total = models.IntegerField()

class GradeCards(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    Semester = models.CharField(max_length = 5)
    Subject_code = models.CharField(max_length = 5)
    Subject_name = models.TextField()
    Credit = models.IntegerField()
    Month_and_year = models.CharField(max_length = 15)
    Grade = models.CharField(max_length = 5)
    SGPA = models.FloatField()
    Status = models.BooleanField(default=False)

class LeaveRequests(models.Model):
    Students = models.ForeignKey(Students,on_delete=models.CASCADE,default=None)
    Faculties = models.ForeignKey(Faculties,on_delete=models.CASCADE,default=None)
    Subjects = models.ForeignKey(Subjects,on_delete=models.CASCADE,default=None)
    Date = models.DateField()
    Hour = models.IntegerField()
    LeaveType = models.CharField(max_length = 15)
    Reason = models.TextField()
    DL_upload = models.FileField(upload_to='pdf_files/')
    Adv_approval = models.BooleanField(default=0)
    Fac_approval = models.BooleanField(default=0)
    Status = models.CharField(max_length = 15)
class pdfconvert(models.Model):
    name_candidate=models.CharField(max_length=300,default="")
    regno=models.CharField(max_length=300,default="")
    clgname=models.CharField(max_length=300,default="")
    branch=models.CharField(max_length=300,default="")
    sem=models.CharField(max_length=300,default="")
    pgm=models.CharField(max_length=300,default="")
    coursname=models.CharField(max_length=3000,default="")
    code=models.CharField(max_length=300,default="")
    grade=models.CharField(max_length=300,default="")
    credits=models.CharField(max_length=300,default="")
    mnthyearofexam=models.CharField(max_length=300,default="")
    totcrd=models.IntegerField(default="1")
    sgpa=models.FloatField(default="1.0")
    def __str__(self):
        return self.name_candidate

RITPROJECT/RITPROJECT/college/collegeapp/templates/hi.html
{% load static %}
<html>
<title>example</title>
<head> <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" /></head>
	<body>
		<h2>HI</h2>
		 <div class="container">
      {% block pagecontent %}
      {% endblock %}
    </div>
	</body>
</html>S

RITPROJECT/RITPROJECT/college/collegeapp/templates/tableadviewinternmark.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>
<head>
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>  
<script>

  $(document).ready(function () {  
    var form = $('.form'),  
    cache_width = form.width(),  
    a4 = [595.28, 841.89]; // for a4 size paper width and height  
    $('#generate_pdf').on('click', function () {  
        $('body').scrollTop(0);  
        generatePDF();  
    });  
    function generatePDF() {  
        getCanvas().then(function (canvas) { 
            var img = canvas.toDataURL("image/png"),  
             doc = new jsPDF({  
                 unit: 'px',  
                 format: 'a4'  
             });  
            doc.addImage(img, 'JPEG', 20, 20);  
            doc.save('Task.pdf');  
            form.width(cache_width);  
        });  
    }  
    function getCanvas() {  
        form.width((a4[0] * 1.33333) - 80).css('max-width', 'none');  
        return html2canvas(form, {  
            imageTimeout: 2000,  
            removeContainer: true  
        });  
    }
});

</script>
<style>
  .hidden-input {
    display: none;
  }
</style>
<body>
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="indexadvisor.html" class="logo d-flex align-items-center">
       <!-- <img src="{% static 'assets/img/logo.png' %}" alt=""> -->
        <span class="d-none d-lg-block">RIT CSE</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
  
  
    <nav class="header-nav ms-auto">
      
  
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/profile_pic.jpg' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">Advisor</span>
          </a><!-- End Profile Iamge Icon -->
  
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'loginpage' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
  
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
  
      </ul>
    </nav><!-- End Icons Navigation -->
  
  </header><!-- End Header -->


    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
    
          <li class="nav-item">
            <a class="nav-link " href="{% url 'indexadvisor' %}">
              <i class="bi bi-grid"></i>
              <span>Dashboard</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'advisorpdview' %}">
              <i class="bi bi-grid"></i>
              <span>View Personal Details of Students</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'adviewinternalmark' %}">
              <i class="bi bi-grid"></i>
              <span>View Internal Marks</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'adviewattendance' %}">
              <i class="bi bi-grid"></i>
              <span>View Attendance</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'leaveapproval' %}">
              <i class="bi bi-grid"></i>
              <span>Approve Duty Leave / Medical Leave</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'result' %}">
              <i class="bi bi-grid"></i>
              <span>Result Analysis</span>
            </a>
          </li>

          <!-- <li class="nav-item"> -->
            <!-- <a class="nav-link " href="{% url 'reportgeneration' %}"> -->
              <!-- <i class="bi bi-grid"></i> -->
              <!-- <span>Report Generation</span> -->
            <!-- </a> -->
          <!-- </li> -->

          <li class="nav-heading">More</li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'contact1' %}">
          <i class="bi bi-envelope"></i>
          <span>Contact</span>
        </a>
      </li><!-- End Contact Page Nav -->
      
        </ul>

    </aside><!-- End Sidebar-->


    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Internal Marks</h1>
            <nav>
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'indexadvisor' %}">Home</a></li>
                <li class="breadcrumb-item">View Internal Marks</li>
              </ol>
            </nav>
          </div><!-- End Page Title -->
      
          <section class="section">
            <div class="row">
              <div class="col-lg-12">
      
                <div class="card">
                  <div class="card-body">
                     
                    <table id="studintern" class="table ">
                    <form class="form" method="POST" action="{% url 'adviewinternalmark' %">

                    <h5 class="card-title">Internal Marks</h5>
              
                      <br>
                       <button style="padding-left:30px;" type="button"  id="generate_pdf" value="Generate PDF" class="btn btn-primary" style=" margin-right: 0;float: right;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-pdf" viewBox="0 0 16 16">
<path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"></path>
<path d="M4.603 12.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.701 19.701 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.187-.012.395-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.065.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.716 5.716 0 0 1-.911-.95 11.642 11.642 0 0 0-1.997.406 11.311 11.311 0 0 1-1.021 1.51c-.29.35-.608.655-.926.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.27.27 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.647 12.647 0 0 1 1.01-.193 11.666 11.666 0 0 1-.51-.858 20.741 20.741 0 0 1-.5 1.05zm2.446.45c.15.162.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.881 3.881 0 0 0-.612-.053zM8.078 5.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"></path>
</svg>
Generate PDF
      </button>
      <h4 style="text-align:center;">Internal Mark</h4>
                      <thead>
                        <tr>
                          <th scope="col">Roll Number</th>
                          <th scope="col">Name</th>

                                         <th>Assignment 1</th>
                <th>Assignment 2</th>

                       <h4>{{facid}}</h4>  
                          <th scope="col">Series Exam 1</th>
                          <th scope="col">Series Exam 2</th>
                          
                           <th scope="col">Attendance</th>
                          
                          <th scope="col">Total</th>
                        </tr>
                      </thead>
                      <tbody>
           {% for student in students %}
            <tr>
                <td>{{ student.Rollno }}</td>
                <td>{{ student.Name }}</td>

                {% for assignment in student.assignmentmarks_set.all %}
                    <td>{{ assignment.Marks }}</td>
                {% endfor %}
                {% for series in student.seriesexammarks_set.all %}
                    {% if series.SeriesExamNo == 1 %}
                        <td>{{ series.Marks }}</td>
                    {% endif %}
                {% endfor %}
                {% for series in student.seriesexammarks_set.all %}
                    {% if series.SeriesExamNo == 2 %}
                        <td>{{ series.Marks }}</td>
                    {% endif %}
                {% endfor %}
                {% if student.internalmarks_set.all %}
            {% with internal_marks=student.internalmarks_set.first %}
            
                <td>{{ internal_marks.Attendancemarks }}</td>
                 <!-- <td>{{ internal_marks.FacultySubjects.Subjects.Subject_name }}</td> -->
                <td>{{ internal_marks.Total }}</td>
            
            </tr>
            {% endwith %}
        {% endif %}
        {% endfor %}
          </tbody>
                    </table> 
                    <!-- End Table with stripped rows -->
   
      <script>
    $(document).ready(function() {
      var $batchselect=$("#sub");

      var $table = $('#studintern'); // Replace 'yourTableId' with the actual ID of your table
      var $tableCells = $table.find('td');
      $batchselect.on('change', function() {
        var selectedbatchId = $(this).val();

        // Show all semester options
        $tableCells.show();

        // Filter semester options based on the selected course
        if (selectedbatchId !== '') {
          $tableCells.each(function() {
            if ($(this).attr('data-batch-id') !== selectedbatchId) {
              $(this).hide();
            }
          });
        }
      });

    
      </script>
                  </div>
                </div>
      
              </div>
            </div>
          </section>

    </main>
</body>
</html>
{% endblock %}